<?php

declare(strict_types=1);

namespace GuessTheFlagBundle\Repository;

use GuessTheFlagBundle\Entity\Flag;

/**
 * FlagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $count
     *
     * @return Flag[]
     */
    public function getRandomFlags(int $count): array
    {
        $qb = $this->createQueryBuilder('f');

        return $qb->addSelect('RAND() as HIDDEN rand')
            ->orderBy('rand')
            ->setMaxResults($count)
            ->getQuery()
            ->getArrayResult();
    }
}
